### ISSUE TITLE
ImportError: cannot import name 'gcd' from 'fractions'

### ISSUE THREAD

**Issue by kuangzhuoran** [PhyloSofS-Team/thoraxe#8]
Hi

I install thoraxe by “python -m pip install thoraxe”
Then when I type ’thoraxe"， I met "ImportError: cannot import name 'gcd' from 'fractions'"

I have installed 'gcd' and 'fractions' by 'pip install'

**Comment by kuangzhuoran** [comment]
![1](https://github.com/user-attachments/assets/e0249e7b-5def-45d6-805c-72f340e034dd)
![2](https://github.com/user-attachments/assets/daebfe29-e52c-41dc-80b2-617a4f9f328e)

**Comment by diegozea** [comment]
Hi @kuangzhuoran 
Thanks for reaching out. The problem is that thoraxe doesn't support Python 3.9. Thoraxe only runs on Python versions from 3.6.1 to 3.8.x. Can you run it using Python 3.8? 
Cheers,
